baseURL = 'https://gabrielcoelho.github.io/'
languageCode = 'pt-br'
title = "dev:Coelho"
copyright = 'Gabriel Coelho Soares' # Used in the footer copyright mention.
enableRobotsTXT = true # IMPORTANT: set to true if you want to use the theme's genAI/LLM web crawler blocking feature.
math = true

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'Anotações'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Gráfico'
    pageRef = '/graph'
    weight = 40

# Author details for the JSON-LD structured data.
  [params.author]
    name = 'Gabriel Coelho Soares'
    email = 'eu@gabrielcoelhosoares.com.br'

  # Homepage setup
  [params.home]
    # Display recent blog posts on the homepage.
    # Default: true
    showRecentPosts = true

    # Set how many recent blog posts to show.
    # Default: 3
    recentPostsLimit = 3

    # Display recent notes on the homepage.
    # Default: true
    showRecentNotes = true

    # Set how many recent notes to show.
    # Default: 5
    recentNotesLimit = 2

# Footer setup
  [params.footer]
    # Specify the Creative Commons license to apply to your content.
    # Options: `by`, `by_sa`, `by_nc`, `by_nc_sa`, `by_nd`, `by_nc_nd`, `zero`, `none`
    # Learn more at https://creativecommons.org/share-your-work/cclicenses/
    # Default: none
    creativeCommonsLicense = 'by_sa'

    # Show Creative Commons icons for the selected license.
    # Default: true
    showCreativeCommonsIcons = true

    # Show a credit link to the Today I Learned theme in the footer.
    # Default: true
    showThemeCredit = true

[markup]
  [markup.highlight]
    noClasses = false
    style = 'gruvbox'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
